In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 


In [58]:
df = pd.read_csv(r'G:\machine learning\Datasets\mushroom\mushrooms.csv')

In [59]:
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [60]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [61]:
df.describe().T

count unique top  freq
class                     8124      2   e  4208
cap-shape                 8124      6   x  3656
cap-surface               8124      4   y  3244
cap-color                 8124     10   n  2284
bruises                   8124      2   f  4748
odor                      8124      9   n  3528
gill-attachment           8124      2   f  7914
gill-spacing              8124      2   c  6812
gill-size                 8124      2   b  5612
gill-color                8124     12   b  1728
stalk-shape               8124      2   t  4608
stalk-root                8124      5   b  3776
stalk-surface-above-ring  8124      4   s  5176
stalk-surface-below-ring  8124      4   s  4936
stalk-color-above-ring    8124      9   w  4464
stalk-color-below-ring    8124      9   w  4384
veil-type                 8124      1   p  8124
veil-color                8124      4   w  7924
ring-number               8124      3   o  7488
ring-type                 8124      5   p  3968
spore-print-color         8124      9   w  2388
population                8124      6   v  4040
habitat                   8124      7   d  3148

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.iloc[:,1:]:
    df[i] = le.fit_transform(df[i])

In [63]:
df

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0        p          5            2          4        1     6                1   
1        e          5            2          9        1     0                1   
2        e          0            2          8        1     3                1   
3        p          5            3          8        1     6                1   
4        e          5            2          3        0     5                1   
...    ...        ...          ...        ...      ...   ...              ...   
8119     e          3            2          4        0     5                0   
8120     e          5            2          4        0     5                0   
8121     e          2            2          4        0     5                0   
8122     p          3            3          4        0     8                1   
8123     e          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0                0          1           4  ...                         2   
1                0          0           4  ...                         2   
2                0          0           5  ...                         2   
3                0          1           5  ...                         2   
4                1          0           4  ...                         2   
...            ...        ...         ...  ...                       ...   
8119             0          0          11  ...                         2   
8120             0          0          11  ...                         2   
8121             0          0           5  ...                         2   
8122             0          1           0  ...                         1   
8123             0          0          11  ...                         2   

      stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                          7                       7          0           2   
1                          7                       7          0           2   
2                          7                       7          0           2   
3                          7                       7          0           2   
4                          7                       7          0           2   
...                      ...                     ...        ...         ...   
8119                       5                       5          0           1   
8120                       5                       5          0           0   
8121                       5                       5          0           1   
8122                       7                       7          0           2   
8123                       5                       5          0           1   

      ring-number  ring-type  spore-print-color  population  habitat  
0               1          4                  2           3        5  
1               1          4                  3           2        1  
2               1          4                  3           2        3  
3               1          4                  2           3        5  
4               1          0                  3           0        1  
...           ...        ...                ...         ...      ...  
8119            1          4                  0           1        2  
8120            1          4                  0           4        2  
8121            1          4                  0           1        2  
8122            1          0                  7           4        2  
8123            1          4                  4           1        2  

[8124 rows x 23 columns]

In [64]:
X = df.iloc[:,1:]

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X = sc.fit_transform(X)
X
 

array([[ 1.02971224,  0.14012794, -0.19824983, ..., -0.67019486,
        -0.5143892 ,  2.03002809],
       [ 1.02971224,  0.14012794,  1.76587407, ..., -0.2504706 ,
        -1.31310821, -0.29572966],
       [-2.08704716,  0.14012794,  1.37304929, ..., -0.2504706 ,
        -1.31310821,  0.86714922],
       ...,
       [-0.8403434 ,  0.14012794, -0.19824983, ..., -1.50964337,
        -2.11182722,  0.28570978],
       [-0.21699152,  0.95327039, -0.19824983, ...,  1.42842641,
         0.28432981,  0.28570978],
       [ 1.02971224,  0.14012794, -0.19824983, ...,  0.16925365,
        -2.11182722,  0.28570978]])

In [66]:
y = df.iloc[:,0].map({'p':1,'e':0})

In [67]:
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64

In [68]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [69]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [70]:
lr.predict(X_test)

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [71]:
lr.score(X_test,y_test)

0.9515996718621821

In [72]:
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf',gamma='auto')
svc.fit(X_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [73]:
svc.predict(X_test)

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [74]:
svc.score(X_test,y_test)

1.0